### ISSUE TITLE
Le module empêche d'éditer certains objets

### ISSUE THREAD

**Issue by Darkriders98** [adgranger/foundryvtt-dnd5e-lang-fr-fr#91]
Le module empêche d'éditer les armes, les équipements et les outils sur la version 12 de foundry et donc la version 3.2.0 de Foundry, voici l'erreur js que j'ai:

```Error: An error occurred while rendering ItemSheet5e 32. data.toObject is not a function
    at Hooks.onError (foundry.js:630:24)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Hooks.onError#lib-wrapper (listeners.js:138:11)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:187:52)
    at foundry.js:5771:13Caused by: TypeError: data.toObject is not a function
    at babele.js:78:75
    at Array.map (<anonymous>)
    at 🎁CONFIG.DatabaseBackend._getDocuments#babele (babele.js:77:27)
    at async CompendiumCollection.getIndex (foundry.js:12947:19)
    at async ItemSheet5e._getItemBaseTypes (item-sheet.mjs:263:24)
    at async ItemSheet5e.getData (item-sheet.mjs:112:18)
    at async ItemSheet5e._render (foundry.js:5814:18)
    at async ItemSheet5e._render (foundry.js:6548:5)
    at async ItemSheet5e._render (foundry.js:7134:5)

**Comment by adgranger** [comment]
Le problème est connus, malheureusement il se situe coté babele.

Le correctif a été fait chez eux le 25 mai dernier, mais il faut attendre la sortie d'une nouvelle release ...
https://gitlab.com/riccisi/foundryvtt-babele/-/commit/cdde3ea8e6597ee07bc6eb8afb64acf4d9e92320

**Comment by adgranger** [comment]
Le problème est connus, malheureusement il se situe coté babele.

Le correctif a été fait chez eux le 25 mai dernier, mais il faut attendre la sortie d'une nouvelle release ...
https://gitlab.com/riccisi/foundryvtt-babele/-/commit/cdde3ea8e6597ee07bc6eb8afb64acf4d9e92320

Merci quand même de l'avoir signalé :)
